//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIResponder.h>

#import "UIWindowSceneDelegate-Protocol.h"

@class UIWindow;

@interface _TtC9AppSecDev13SceneDelegate : UIResponder <UIWindowSceneDelegate>
{
    // Error parsing type: , name: window
}

- (void).cxx_destruct;
- (id)init;
- (void)sceneDidEnterBackground:(id)arg1;
- (void)sceneWillEnterForeground:(id)arg1;
- (void)sceneWillResignActive:(id)arg1;
- (void)sceneDidBecomeActive:(id)arg1;
- (void)sceneDidDisconnect:(id)arg1;
- (void)scene:(id)arg1 willConnectToSession:(id)arg2 options:(id)arg3;
@property(nonatomic, retain) UIWindow *window; // @synthesize window;

@end

