# Uncomment the next line to define a global platform for your project

platform :ios, '11.0'
use_frameworks!
inhibit_all_warnings!

target 'AppSecDev' do

  # Pods for AppSecDev
  pod 'SwiftyRSA', '= 1.6.0'
  pod 'CryptoSwift', '= 1.3.2'
  pod 'PromiseKit', '= 6.13.1'
  pod 'Alamofire', '= 5.2.1'
#  pod 'EllipticCurveKeyPair'
#  pod "EosioSwiftEcc"
  pod "BlueECC", '= 1.2.5'
end
